name: Actions workflow

# on: ["push","pull_request"]

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: Simple js Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Arpit
      - name: Log time
        run: echo "${{steps.greet.outputs.time}}"